kind: Deployment
apiVersion: apps/v1
metadata:
  name: sadir-integration-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sadir-integration-sidecar
  template:
    metadata:
      labels:
        app: sadir-integration-sidecar
    spec:
      containers:
        - name: my-java-springboot
          image: yashesh/sdr-integration-sidecar:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: sadir-integration-sidecar-svc
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sadir-integration-sidecar